name: vite-press-deploy
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [ push ]

jobs:
  Explore-Gitea-Actions:
    runs-on: default_label
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: https://gitee.com/mirror-actions/checkout@v4
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
      - name: Install dependencies
        run: |
          pnpm install
      - name: Build with VitePress
        run: |
          pnpm docs:build
      - name: Clear output directory
        run: |
          if (Test-Path -Path "C:\output\dist") {
            Remove-Item -Path "C:\output\dist\*" -Recurse -Force
          }else{
            New-Item -Path "C:\output\dist" -ItemType Directory
          }
        shell: powershell
      - name: Copy repository to C:\output
        run: |
          Copy-Item -Path "${{ gitea.workspace }}\docs\dist\*" -Destination "C:\output\dist" -Recurse -Force
        shell: powershell

      - run: echo "🍏 This job's status is ${{ job.status }}."
